// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Totten.Solutions.WolfMonitor.Infra.ORM.Contexts;

namespace Totten.Solutions.WolfMonitor.Infra.ORM.Migrations.Auth
{
    [DbContext(typeof(AuthContext))]
    [Migration("20200411212127_AddColumnsReferedRecoverPassword")]
    partial class AddColumnsReferedRecoverPassword
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Totten.Solutions.WolfMonitor.Domain.Features.UsersAggregation.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedIn");

                    b.Property<int>("Level");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("Removed");

                    b.Property<DateTime>("UpdatedIn");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c2b5f932-2486-40c2-acd4-d4dfaee23c0a"),
                            CreatedIn = new DateTime(2020, 4, 11, 18, 21, 26, 695, DateTimeKind.Local).AddTicks(7639),
                            Level = 0,
                            Name = "Agent",
                            Removed = false,
                            UpdatedIn = new DateTime(2020, 4, 11, 18, 21, 26, 696, DateTimeKind.Local).AddTicks(4672)
                        },
                        new
                        {
                            Id = new Guid("a0ecc468-516a-46a7-8134-b65857c1edb8"),
                            CreatedIn = new DateTime(2020, 4, 11, 18, 21, 26, 698, DateTimeKind.Local).AddTicks(2818),
                            Level = 1,
                            Name = "User",
                            Removed = false,
                            UpdatedIn = new DateTime(2020, 4, 11, 18, 21, 26, 698, DateTimeKind.Local).AddTicks(2832)
                        },
                        new
                        {
                            Id = new Guid("f91a2366-c469-412a-9197-976a90516272"),
                            CreatedIn = new DateTime(2020, 4, 11, 18, 21, 26, 698, DateTimeKind.Local).AddTicks(3043),
                            Level = 2,
                            Name = "Admin",
                            Removed = false,
                            UpdatedIn = new DateTime(2020, 4, 11, 18, 21, 26, 698, DateTimeKind.Local).AddTicks(3044)
                        },
                        new
                        {
                            Id = new Guid("259c8774-2813-4f73-9b63-fc131afbbbc4"),
                            CreatedIn = new DateTime(2020, 4, 11, 18, 21, 26, 698, DateTimeKind.Local).AddTicks(3088),
                            Level = 3,
                            Name = "System",
                            Removed = false,
                            UpdatedIn = new DateTime(2020, 4, 11, 18, 21, 26, 698, DateTimeKind.Local).AddTicks(3089)
                        });
                });

            modelBuilder.Entity("Totten.Solutions.WolfMonitor.Domain.Features.UsersAggregation.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CompanyId");

                    b.Property<string>("Cpf")
                        .IsRequired();

                    b.Property<DateTime>("CreatedIn");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("Language")
                        .IsRequired();

                    b.Property<string>("LastName");

                    b.Property<string>("Login")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("RecoverSolicitationCode");

                    b.Property<bool>("Removed");

                    b.Property<Guid>("RoleId");

                    b.Property<string>("Token");

                    b.Property<string>("TokenSolicitationCode");

                    b.Property<DateTime>("UpdatedIn");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5c37de9d-7eb2-4d2b-a4ae-a5248bd6bfce"),
                            CompanyId = new Guid("c576cf93-370c-4464-21f9-08d763d27d75"),
                            Cpf = "10685805425",
                            CreatedIn = new DateTime(2020, 4, 11, 18, 21, 26, 724, DateTimeKind.Local).AddTicks(5352),
                            Email = "aleffmds@gmail.com",
                            FirstName = "Aleff",
                            Language = "pt-BR",
                            LastName = "Moura da Silva",
                            Login = "aleffmoura",
                            Password = "I2uzfR1PyNB3qujyRKe/fvFvXQzylgU+UUIARcpeLkI=",
                            Removed = false,
                            RoleId = new Guid("259c8774-2813-4f73-9b63-fc131afbbbc4"),
                            UpdatedIn = new DateTime(2020, 4, 11, 18, 21, 26, 724, DateTimeKind.Local).AddTicks(5369)
                        });
                });

            modelBuilder.Entity("Totten.Solutions.WolfMonitor.Domain.Features.UsersAggregation.User", b =>
                {
                    b.HasOne("Totten.Solutions.WolfMonitor.Domain.Features.UsersAggregation.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
