// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Totten.Solutions.WolfMonitor.Infra.ORM.Contexts;

namespace Totten.Solutions.WolfMonitor.Infra.ORM.Migrations.Auth
{
    [DbContext(typeof(AuthContext))]
    partial class AuthContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Totten.Solutions.WolfMonitor.Domain.Features.Users.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedIn");

                    b.Property<int>("Level");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("Removed");

                    b.Property<DateTime>("UpdatedIn");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("020894b7-53f1-468a-9695-a2b6c47406ce"),
                            CreatedIn = new DateTime(2019, 11, 8, 20, 27, 37, 456, DateTimeKind.Local).AddTicks(6569),
                            Level = 0,
                            Name = "Agent",
                            Removed = false,
                            UpdatedIn = new DateTime(2019, 11, 8, 20, 27, 37, 463, DateTimeKind.Local).AddTicks(590)
                        },
                        new
                        {
                            Id = new Guid("4ef84fad-8dee-4395-bae1-65fa8fa11dcc"),
                            CreatedIn = new DateTime(2019, 11, 8, 20, 27, 37, 465, DateTimeKind.Local).AddTicks(9185),
                            Level = 1,
                            Name = "User",
                            Removed = false,
                            UpdatedIn = new DateTime(2019, 11, 8, 20, 27, 37, 465, DateTimeKind.Local).AddTicks(9229)
                        },
                        new
                        {
                            Id = new Guid("d300b446-2fd4-4059-a074-6af0ba419cea"),
                            CreatedIn = new DateTime(2019, 11, 8, 20, 27, 37, 465, DateTimeKind.Local).AddTicks(9410),
                            Level = 2,
                            Name = "Administrador",
                            Removed = false,
                            UpdatedIn = new DateTime(2019, 11, 8, 20, 27, 37, 465, DateTimeKind.Local).AddTicks(9429)
                        },
                        new
                        {
                            Id = new Guid("05f62ca8-462f-4796-bab1-ed083cebf096"),
                            CreatedIn = new DateTime(2019, 11, 8, 20, 27, 37, 465, DateTimeKind.Local).AddTicks(9478),
                            Level = 2,
                            Name = "System",
                            Removed = false,
                            UpdatedIn = new DateTime(2019, 11, 8, 20, 27, 37, 465, DateTimeKind.Local).AddTicks(9498)
                        });
                });

            modelBuilder.Entity("Totten.Solutions.WolfMonitor.Domain.Features.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CompanyId");

                    b.Property<string>("Cpf")
                        .IsRequired();

                    b.Property<DateTime>("CreatedIn");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("Language")
                        .IsRequired();

                    b.Property<string>("LastName");

                    b.Property<string>("Login")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<bool>("Removed");

                    b.Property<Guid>("RoleId");

                    b.Property<DateTime>("UpdatedIn");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e0704212-13e5-4809-9b45-5d1f222eceec"),
                            CompanyId = new Guid("c576cf93-370c-4464-21f9-08d763d27d75"),
                            Cpf = "10685805425",
                            CreatedIn = new DateTime(2019, 11, 8, 20, 27, 37, 492, DateTimeKind.Local).AddTicks(7594),
                            Email = "aleffmds@gmail.com",
                            FirstName = "Aleff",
                            Language = "pt-BR",
                            LastName = "Moura da Silva",
                            Login = "alefmoura",
                            Password = "YWLA/fjq/N2i5CmP6+HJMXDslpQwLLP2tHl4E9NaM8w=",
                            Removed = false,
                            RoleId = new Guid("05f62ca8-462f-4796-bab1-ed083cebf096"),
                            UpdatedIn = new DateTime(2019, 11, 8, 20, 27, 37, 492, DateTimeKind.Local).AddTicks(7663)
                        });
                });

            modelBuilder.Entity("Totten.Solutions.WolfMonitor.Domain.Features.Users.User", b =>
                {
                    b.HasOne("Totten.Solutions.WolfMonitor.Domain.Features.Users.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
