// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Totten.Solutions.WolfMonitor.Infra.ORM.Contexts;

namespace Totten.Solutions.WolfMonitor.Infra.ORM.Migrations
{
    [DbContext(typeof(AuthContext))]
    partial class AuthContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Totten.Solutions.WolfMonitor.Domain.Features.UsersAggregation.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedIn");

                    b.Property<int>("Level");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("Removed");

                    b.Property<DateTime>("UpdatedIn");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f2b6aeb4-9cda-4be0-9237-fc50a0c06b97"),
                            CreatedIn = new DateTime(2020, 6, 7, 22, 55, 50, 200, DateTimeKind.Local).AddTicks(2339),
                            Level = 0,
                            Name = "Agent",
                            Removed = false,
                            UpdatedIn = new DateTime(2020, 6, 7, 22, 55, 50, 201, DateTimeKind.Local).AddTicks(1532)
                        },
                        new
                        {
                            Id = new Guid("1f611ece-7649-49f5-a933-e3b5e6f228b8"),
                            CreatedIn = new DateTime(2020, 6, 7, 22, 55, 50, 203, DateTimeKind.Local).AddTicks(5471),
                            Level = 1,
                            Name = "User",
                            Removed = false,
                            UpdatedIn = new DateTime(2020, 6, 7, 22, 55, 50, 203, DateTimeKind.Local).AddTicks(5488)
                        },
                        new
                        {
                            Id = new Guid("f91a2366-c469-412a-9197-976a90516272"),
                            CreatedIn = new DateTime(2020, 6, 7, 22, 55, 50, 203, DateTimeKind.Local).AddTicks(5630),
                            Level = 2,
                            Name = "Admin",
                            Removed = false,
                            UpdatedIn = new DateTime(2020, 6, 7, 22, 55, 50, 203, DateTimeKind.Local).AddTicks(5632)
                        },
                        new
                        {
                            Id = new Guid("682ba438-61a7-4fc3-99fd-0d343c05d08f"),
                            CreatedIn = new DateTime(2020, 6, 7, 22, 55, 50, 203, DateTimeKind.Local).AddTicks(5680),
                            Level = 3,
                            Name = "System",
                            Removed = false,
                            UpdatedIn = new DateTime(2020, 6, 7, 22, 55, 50, 203, DateTimeKind.Local).AddTicks(5681)
                        });
                });

            modelBuilder.Entity("Totten.Solutions.WolfMonitor.Domain.Features.UsersAggregation.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CompanyId");

                    b.Property<string>("Cpf")
                        .IsRequired();

                    b.Property<DateTime>("CreatedIn");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("Language")
                        .IsRequired();

                    b.Property<DateTime?>("LastLogin");

                    b.Property<string>("LastName");

                    b.Property<string>("Login")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("RecoverSolicitationCode");

                    b.Property<bool>("Removed");

                    b.Property<Guid>("RoleId");

                    b.Property<string>("Token");

                    b.Property<string>("TokenSolicitationCode");

                    b.Property<DateTime>("UpdatedIn");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f75a1881-0fd6-4273-9d23-c59018788201"),
                            CompanyId = new Guid("c576cf93-370c-4464-21f9-08d763d27d75"),
                            Cpf = "11111111111",
                            CreatedIn = new DateTime(2020, 6, 7, 22, 55, 50, 225, DateTimeKind.Local).AddTicks(8803),
                            Email = "aleffmds@gmail.com",
                            FirstName = "Aleff",
                            Language = "pt-BR",
                            LastName = "Moura da Silva",
                            Login = "aleffmoura",
                            Password = "I2uzfR1PyNB3qujyRKe/fvFvXQzylgU+UUIARcpeLkI=",
                            Removed = false,
                            RoleId = new Guid("682ba438-61a7-4fc3-99fd-0d343c05d08f"),
                            UpdatedIn = new DateTime(2020, 6, 7, 22, 55, 50, 225, DateTimeKind.Local).AddTicks(9350)
                        });
                });

            modelBuilder.Entity("Totten.Solutions.WolfMonitor.Domain.Features.UsersAggregation.User", b =>
                {
                    b.HasOne("Totten.Solutions.WolfMonitor.Domain.Features.UsersAggregation.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
