// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Totten.Solutions.WolfMonitor.Infra.ORM.Contexts;

namespace Totten.Solutions.WolfMonitor.Infra.ORM.Migrations
{
    [DbContext(typeof(AuthContext))]
    partial class AuthContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Totten.Solutions.WolfMonitor.Domain.Features.UsersAggregation.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedIn");

                    b.Property<int>("Level");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("Removed");

                    b.Property<DateTime>("UpdatedIn");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cedb7efe-3558-4af3-baaf-7236ffeab75e"),
                            CreatedIn = new DateTime(2020, 6, 9, 20, 57, 0, 372, DateTimeKind.Local).AddTicks(6597),
                            Level = 0,
                            Name = "Agent",
                            Removed = false,
                            UpdatedIn = new DateTime(2020, 6, 9, 20, 57, 0, 373, DateTimeKind.Local).AddTicks(3340)
                        },
                        new
                        {
                            Id = new Guid("9f2d4720-72fc-4a3b-b9ca-b4f939186497"),
                            CreatedIn = new DateTime(2020, 6, 9, 20, 57, 0, 375, DateTimeKind.Local).AddTicks(412),
                            Level = 1,
                            Name = "User",
                            Removed = false,
                            UpdatedIn = new DateTime(2020, 6, 9, 20, 57, 0, 375, DateTimeKind.Local).AddTicks(423)
                        },
                        new
                        {
                            Id = new Guid("f91a2366-c469-412a-9197-976a90516272"),
                            CreatedIn = new DateTime(2020, 6, 9, 20, 57, 0, 375, DateTimeKind.Local).AddTicks(535),
                            Level = 2,
                            Name = "Admin",
                            Removed = false,
                            UpdatedIn = new DateTime(2020, 6, 9, 20, 57, 0, 375, DateTimeKind.Local).AddTicks(537)
                        },
                        new
                        {
                            Id = new Guid("4fb7fbac-f766-42e3-bb2a-f3fc4c4577d6"),
                            CreatedIn = new DateTime(2020, 6, 9, 20, 57, 0, 375, DateTimeKind.Local).AddTicks(574),
                            Level = 3,
                            Name = "System",
                            Removed = false,
                            UpdatedIn = new DateTime(2020, 6, 9, 20, 57, 0, 375, DateTimeKind.Local).AddTicks(575)
                        });
                });

            modelBuilder.Entity("Totten.Solutions.WolfMonitor.Domain.Features.UsersAggregation.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CompanyId");

                    b.Property<string>("Cpf")
                        .IsRequired();

                    b.Property<DateTime>("CreatedIn");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("Language")
                        .IsRequired();

                    b.Property<DateTime?>("LastLogin");

                    b.Property<string>("LastName");

                    b.Property<string>("Login")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("RecoverSolicitationCode");

                    b.Property<bool>("Removed");

                    b.Property<Guid>("RoleId");

                    b.Property<string>("Token");

                    b.Property<string>("TokenSolicitationCode");

                    b.Property<DateTime>("UpdatedIn");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f75a1881-0fd6-4273-9d23-c59018788201"),
                            CompanyId = new Guid("c576cf93-370c-4464-21f9-08d763d27d75"),
                            Cpf = "11111111111",
                            CreatedIn = new DateTime(2020, 6, 9, 20, 57, 0, 405, DateTimeKind.Local).AddTicks(1590),
                            Email = "aleffmds@gmail.com",
                            FirstName = "Aleff",
                            Language = "pt-BR",
                            LastName = "Moura da Silva",
                            Login = "aleffmoura",
                            Password = "I2uzfR1PyNB3qujyRKe/fvFvXQzylgU+UUIARcpeLkI=",
                            Removed = false,
                            RoleId = new Guid("4fb7fbac-f766-42e3-bb2a-f3fc4c4577d6"),
                            UpdatedIn = new DateTime(2020, 6, 9, 20, 57, 0, 405, DateTimeKind.Local).AddTicks(3125)
                        });
                });

            modelBuilder.Entity("Totten.Solutions.WolfMonitor.Domain.Features.UsersAggregation.User", b =>
                {
                    b.HasOne("Totten.Solutions.WolfMonitor.Domain.Features.UsersAggregation.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
